[tool.ruff]
line-length = 120
select = [
	'E', 'F', 'I',
	'COM', 'Q',
	'RUF',
]
ignore = ['E101']
[tool.ruff.flake8-quotes]
inline-quotes = 'single'
multiline-quotes = 'single'
[tool.ruff.isort]
lines-after-imports = 1
